// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('registerExistingUser', function() {
  //this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('registerExistingUser', async function() {
    await driver.get("https://armchair-athletes-live-sports-c-ofsyvtifhq-uc.a.run.app/home")
    await driver.manage().window().setRect({ width: 1492, height: 997 })
    await driver.findElement(By.css("button:nth-child(4)")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("joshtest")
    await driver.findElement(By.css(".form-floating:nth-child(2) > .form-control")).click()
    await driver.findElement(By.css(".form-floating:nth-child(2) > .form-control")).sendKeys("test")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("josh@test.test")
    await driver.findElement(By.css(".btn")).click()
    await new Promise((r) => setTimeout(r, 2000));  //wait for alert message
    assert((await driver.switchTo().alert().getText()) == "This email already has an account associated with it.")
    })
})
