// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('navigateHomeTitle', function() {
  //this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('navigateHomeTitle', async function() {
    await driver.get("https://armchair-athletes-live-sports-c-ofsyvtifhq-uc.a.run.app/home")
    await driver.manage().window().setRect({ width: 1492, height: 997 })
    await driver.findElement(By.css("div:nth-child(1) > .mainButtons > button")).click()
    await driver.findElement(By.css("h1")).click()
    await driver.findElement(By.css(".welcome")).click()
    {
      const elements = await driver.findElements(By.css(".welcome"))
      assert(elements.length)
    }
    await driver.close()
  })
})
