// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('guestViewGames', function() {
  //this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('guestViewGames', async function() {
    await driver.get("https://armchair-athletes-live-sports-c-ofsyvtifhq-uc.a.run.app/home")
    await driver.manage().window().setRect({ width: 1492, height: 997 })
    await driver.findElement(By.css(".drop:nth-child(4) .dropbtn")).click()
    await driver.findElement(By.css(".dropitem:nth-child(1)")).click()
    await new Promise((r) => setTimeout(r, 2000));
    await driver.findElement(By.css(".wg_league")).click()
    {
      const elements = await driver.findElements(By.css(".wg_league"))
      assert(elements.length)
    }
    await driver.close()
  })
})
