// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Successful Login', function() {
  //this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Successful Login', async function() {
    await driver.get("https://armchair-athletes-live-sports-c-ofsyvtifhq-uc.a.run.app/home")
    await driver.manage().window().setRect({ width: 1060, height: 815 })
    await driver.findElement(By.css("div:nth-child(1) > .mainButtons > button")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("email@email.com")
    await driver.findElement(By.css(".ng-untouched")).click()
    await driver.findElement(By.css(".ng-untouched")).sendKeys("email")
    await driver.findElement(By.css(".ng-untouched")).sendKeys(Key.ENTER)
    await new Promise((r) => setTimeout(r, 1000));
    await driver.findElement(By.css(".welcome")).click()
    {
      const elements = await driver.findElements(By.css(".welcome"))
      assert(elements.length)
    }
  })
})
